version: "3.8"

services:
  pgdb:
    image: postgres:alpine
    container_name: "pgdb"
    restart: "always"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PWD
    ports:
      - "$DB_PORT:5432"
    volumes:
      - $DB_VOLUME_DATA:/var/lib/postgresql/data

  auth-app:
    build: ../.
    container_name: "$AUTH_CONTAINER"
    restart: "always"
    env_file:
      - .env
    environment:
      APP_MODE: "prod"
    ports:
      - "$AUTH_SERVICE_PORT:8080"
    depends_on:
      - pgdb
